### ISSUE TITLE
Payfast doesnt show on Checkout page

### ISSUE THREAD

**Issue by Yoshuwa** [PayFast/mod-osclass#1]
Hi, thank you for developing a payfast module for osclass,
I downloaded and installed it, everything looks fine but on the Checkout page there is no payfast button i also checked my inspect element and nothing seems to be there
warmregards

**Comment by Brendon-P** [comment]
Hi
Thank you for contacting us, please can you submit a ticket to support@payfast.co.za and one of our developers will get back to you as soon as possible.
Regards
The PayFast Team

**Comment by Yoshuwa** [comment]
Thank you! I will
